default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        exclude: ^K8S/templates/
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: bash -c 'pytest -v -m unit'
  #       language: system
  #       pass_filenames: false
  #       verbose: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        additional_dependencies: ["types-PyYAML", "types-requests"]
